title: POSMall Warehouses
modelClass: KodZero\POSMall\Models\Warehouse
list: $/kodzero/posmall/models/warehouse/columns.yaml
recordUrl: 'kodzero/posmall/warehouses/update/:id'
noRecordsMessage: backend::lang.list.no_records
recordsPerPage: 20
showSetup: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: backend::lang.list.search_prompt
