title: 'kodzero.posmall::lang.common.addresses'
modelClass: KodZero\POSMall\Models\Address
list: $/kodzero/posmall/models/address/columns.yaml
recordUrl: 'kodzero/posmall/addresses/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: created_at
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
