title: 'kodzero.posmall::lang.common.property_groups'
modelClass: KodZero\POSMall\Models\PropertyGroup
list: $/kodzero/posmall/models/propertygroup/columns.yaml
recordUrl: 'kodzero/posmall/propertygroups/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: sort_order
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
structure:
    showTree: false
    showReorder: true
    treeExpanded: true
    maxDepth: 1