title: 'kodzero.posmall::lang.common.custom_fields'
modelClass: KodZero\POSMall\Models\CustomField
list: $/kodzero/posmall/models/customfield/columns.yaml
recordUrl: 'kodzero/posmall/customfields/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
