title: 'kodzero.posmall::lang.common.discounts'
modelClass: KodZero\POSMall\Models\Discount
list: $/kodzero/posmall/models/discount/columns.yaml
recordUrl: 'kodzero/posmall/discounts/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
showSorting: 1
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
