title: Services
modelClass: KodZero\POSMall\Models\Service
list: $/kodzero/posmall/models/service/columns.yaml
recordUrl: 'kodzero/posmall/services/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: name
    direction: asc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
